name: Tests with Memgraph and PHP^8.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  memgraph-tests-2204:
    runs-on: ubuntu-22.04
    name: "Running Integration tests for PHP ${{ matrix.php-version }} and Memgraph"
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2']

    services:
      memgraph:
        image: memgraph/memgraph:latest
        ports:
          - 7687:7687

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, sockets, pdo
          coverage: xdebug
          ini-values: max_execution_time=0

      - name: Install dependencies
        run: composer install --no-progress

      - name: Test with phpunit
        env:
          BOLT_VERSION: 4.1
        run: vendor/bin/phpunit --configuration phpunit.xml --testsuite PDO
